# Generated by Django 4.1.6 on 2023-04-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_cart_account_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cart',
        ),
    ]
