# Generated by Django 4.1.6 on 2023-04-25 10:39

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_cart_abstractordercontainer_orders'),
        ('account', '0003_remove_account_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cart',
            field=models.OneToOneField(default=store.models.Cart.get_new, on_delete=django.db.models.deletion.CASCADE, to='store.cart', verbose_name='Products in cart'),
        ),
    ]
