# Generated by Django 4.1.6 on 2023-04-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='account',
            name='postal_code',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(default='', max_length=99),
        ),
    ]
