# Generated by Django 4.1.6 on 2023-03-01 20:44

from django.db import migrations, models


def migrate_to_materials(apps, schema_editor):
    Knife = apps.get_model('store', 'Knife')

    Knife.objects.all().update(materials="Oak wood, Steel")


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_spike_thickness_melee_edge_thickness'),
    ]

    operations = [
        migrations.AlterField('Flashlight', 'materials', models.CharField(max_length=99, default="")),
        migrations.AddField('Knife', 'materials', models.CharField(max_length=99, default="")),
        migrations.AddField('Melee', 'materials', models.CharField(max_length=99, default="")),
        migrations.RunPython(migrate_to_materials),
    ]