# Generated by Django 4.1.6 on 2023-03-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_add_materials_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_filter',
        ),
        migrations.AddField(
            model_name='souvenir',
            name='materials',
            field=models.CharField(default='', max_length=99, null=True),
        ),
    ]
