# Generated by Django 4.1.6 on 2023-04-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_altogether',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
