# Generated by Django 4.1.6 on 2023-04-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_buy_altogether'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
