# Generated by Django 4.1.6 on 2023-04-25 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_abstractordercontainer_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('abstractordercontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.abstractordercontainer')),
            ],
            options={
                'abstract': False,
            },
            bases=('store.abstractordercontainer',),
        ),
        migrations.AddField(
            model_name='abstractordercontainer',
            name='orders',
            field=models.ManyToManyField(to='store.order'),
        ),
    ]
