# Generated by Django 4.1.6 on 2023-04-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_cart_abstractordercontainer_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='quantity',
        ),
    ]
